version: '2'
services:
    couplemeals-app:
        image: couplemeals
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://couplemeals-postgresql:5432/CoupleMeals
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    couplemeals-postgresql:
        extends:
            file: postgresql.yml
            service: couplemeals-postgresql
